// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// import './globals.css'

// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'My App',
//   description: 'Event Management Web App',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// // import { ClerkProvider } from "@clerk/clerk-react";

// const poppins = Poppins({
//    subsets: ["latin"],
//   weight: ['400','500','600','700'],
//  variable:'--font-poppins',  });

// export const metadata: Metadata = {
//   title: "Your Event App",
//   description: "Event management web application",
//   icons:{
//     icon:'/assets/images/logo.jpeg'

//   }
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//   <ClerkProvider>
//     <html lang="en" suppressHydrationWarning>
//       <body className={poppins.variable}>{children}</body>
//     </html>
// </ClerkProvider>
//   );
// }

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Your Event App",
  description: "Event management web application",
  icons: {
    icon: "/assets/images/logo.jpeg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ===== Temporary env-test snippet =====
  if (typeof window !== "undefined" && new URLSearchParams(window.location.search).has("env-test")) {
    console.log(
      "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:",
      process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    );
    alert(
      "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: " +
        process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    );
  }
  // ===== End of temporary snippet =====

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={poppins.variable}>{children}</body>
      </html>
    </ClerkProvider>
  );
}


